[project]
name = "sysml-v2"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "astropy>=5.3.4",
 "setuptools>=80.9.0",
 "sysml2py>=0.5.3",
]
